### ISSUE TITLE
Clean old release on server

### ISSUE THREAD

**Issue by masev** [octower/octower#4]
Add a configuration to automatically clean release older than X day on the server in order to not sature disk space.

**Comment by wpottier** [comment]
Now (since b115f78ec5eaed9245095411afac675c6ebe1aa4) you have a command to clean some release on the server.
`octower.phar server:release:clean`

The number of release kept by the command were configured by setting the "max-number-release" config on the server :
https://getoctower.org/doc/04-server-side-concepts.md

**Comment by masev** [comment]
@wpottier Can you add an argument to "force" cleaning so that the script doesn't ask for a user confirmation (I'd like to script the cleaning) ?

**Comment by wpottier** [comment]
@masev done and available in the latest snapshot
